# Generated by Django 4.2.5 on 2023-10-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultingstudent',
            name='due_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
